apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ml-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ouzlaye/ml_project_backend
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: ml_project
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ml-project
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    app: backend
